insert into sous_categorie values (1, 1,'Fruits frais', 7);
insert into sous_categorie values (2, 1,'Fruits secs', 120);
insert into sous_categorie values (3, 1,'Fruits transformes',0);
insert into sous_categorie values (4, 2,'Legumes frais', 7);
insert into sous_categorie values (5, 3,'Cereales sucrees', 7);
insert into sous_categorie values (6, 3,'Cereales salees', 30);
insert into sous_categorie values (7, 3,'Cereales brutes', 120);
insert into sous_categorie values (8, 4,'Pains', 0);
insert into sous_categorie values (9, 5,'Biscuits sucres', 60);
insert into sous_categorie values (10, 5,'Biscuits sales', 60);
insert into sous_categorie values (11, 6,'Pates fraiches', 0);
insert into sous_categorie values (12, 6, 'Pates seches', 120);
insert into sous_categorie values (13, 7,'Viandes crues', 0);
insert into sous_categorie values (14, 7,'Viandes preparees', 0);
insert into sous_categorie values (15, 7,'Charcuteries', 0);
insert into sous_categorie values (16, 8,'Poissons crus', 0);
insert into sous_categorie values (17, 8,'Poissons prepares', 0);
insert into sous_categorie values (18, 9,'Oeufs', 0);
insert into sous_categorie values (19, 10,'Fromages a pate molle', 0);
insert into sous_categorie values (20, 10,'Fromages a pate pressee', 30);
insert into sous_categorie values (21, 10,'Laits', 0);
insert into sous_categorie values (22, 10,'Yaourts', 21);
insert into sous_categorie values (23, 10,'Fromages blancs', 7);
insert into sous_categorie values (24, 10,'Beurres et margarines', 14);
insert into sous_categorie values (25, 10,'Cremes', 0);
insert into sous_categorie values (26, 11,'Huiles', 0);
insert into sous_categorie values (27, 12,'Patisserie', 0);
insert into sous_categorie values (28, 12,'Bonbons', 120);
insert into sous_categorie values (29, 12,'Autres', 120);
insert into sous_categorie values (30, 12,'Cremes desserts', 120);
insert into sous_categorie values (31, 13, 'Eaux', 0);
insert into sous_categorie values (32, 13, 'Sodas', 0);
insert into sous_categorie values (33, 13, 'Jus de fruits', 0);
insert into sous_categorie values (34, 13, 'Boissons alcoolisees', 0);
insert into sous_categorie values (35, 14,'Sels', 120);
insert into sous_categorie values (36, 14,'Epices', 120);
insert into sous_categorie values (37, 14,'Vinaigres', 120);
insert into sous_categorie values (38, 14,'Sauces', 0);
insert into sous_categorie values (39, 14,'Autres', 0);
insert into sous_categorie values (40, 15,'Aperitifs', 0);
insert into sous_categorie values (41, 16,'Plats prepares', 0);
insert into sous_categorie values (42, 17,'Autres', 0);
insert into sous_categorie values (43, 18,'OpenFoodFacts', 0);

commit;
