insert into Produit values (1,13, 'Agneau (epaule)', '0','/resources/produits/images/epauleagneau.jpg');
insert into Produit values (2,13, 'aiguillette canard' , '0', '/resources/produits/images/aiguillettecanard.jpg');
insert into Produit values (3,14, 'Gesier confits', '0', '/resources/produits/images/gesierconfit.jpg');
insert into Produit values (4,14, 'Gesier de volaille', '0', '/resources/produits/images/gesiervolaille.jpg');
insert into Produit values (5,13, 'Gigot d agneau', '0', '/resources/produits/images/gigotagneau.jpg');
insert into Produit values (6,16, 'Bar', '0', '/resources/produits/images/bar.jpg');
insert into Produit values (7,16, 'Barbue' , '0', '/resources/produits/images/barbue.jpg');
insert into Produit values (8,16, 'Brochet' , '0', '/resources/produits/images/brochet.jpg');
insert into Produit values (9,16, 'Coquille St Jacques' , '0', '/resources/produits/images/saintjacques.jpg');
insert into Produit values (10,4, 'Ail' , '0', '/resources/produits/images/ail.jpg');
insert into Produit values (11,4, 'Artichaut' , '0', '/resources/produits/images/artichaut.jpg');
insert into Produit values (12,24, 'Beurre' , '0', '/resources/produits/images/buerre.jpg');
insert into Produit values (13,24, 'Beurre allege' , '0', '/resources/produits/images/buerre.jpg');
insert into Produit values (14,21, 'Lait entier' , '0', '/resources/produits/images/lait.jpg');
insert into Produit values (15,26, 'Huile d Olive' , '0', '/resources/produits/images/huileolive.jpg');
insert into Produit values (16,1, 'Ananas' , '0', '/resources/produits/images/ananas.jpg');
insert into Produit values (17,1, 'Banane' , '0', '/resources/produits/images/banane.jpg');
insert into Produit values (18,8, 'baguette' , '0', '/resources/produits/images/baguette.jpg');
insert into Produit values (19,12, 'Pates' , '0', '/resources/produits/images/pates.jpg');
insert into Produit values (20,29, 'glace' , '0', '/resources/produits/images/glace.jpg');
insert into Produit values (21,35, 'sel' , '0', '/resources/produits/images/sel.jpg');
insert into Produit values (22,36, 'epice' , '0', '/resources/produits/images/epices.jpg');
insert into Produit values (23,37, 'vinaigre' , '0', '/resources/produits/images/vinaigre.jpg');
insert into Produit values (24,38, 'mayonnaise' , '0', '/resources/produits/images/mayonnaise.jpg');
insert into Produit values (25,38, 'ketchup' , '0', '/resources/produits/images/ketchup.jpg');
insert into Produit values (26,38, 'Moutarde' , '0', '/resources/produits/images/moutarde.jpg');
insert into Produit values (27,31, 'eau plate' , '0', '/resources/produits/images/eau.jpg');
insert into Produit values (28,31, 'eau gazeuse ', '0', '/resources/produits/images/eau.jpg');
insert into Produit values (29,33, 'jus de fruit' , '0', '/resources/produits/images/jus.jpg');
insert into Produit values (30,34, 'alcool' , '0', '/resources/produits/images/alcool.jpg');
insert into Produit values (31,32, 'soda', '0', '/resources/produits/images/soda.jpg');
insert into Produit values (32,9, 'gateaux secs' , '0', '/resources/produits/images/gateausec.jpg');
insert into Produit values (33,9, 'gateaux au chocolat' , '0', '/resources/produits/images/gateauchocolat.jpg');
insert into Produit values (34,9, 'gateaux aux fruits' , '0', '/resources/produits/images/gateaufruit.jpg');
insert into Produit values (35,9, 'cookies' , '0', '/resources/produits/images/coockie.jpg');
insert into Produit values (36,1,'Abricot ', '0', '/resources/produits/images/abricot.jpg');
insert into Produit values (37,1,'Amande ', '0', '/resources/produits/images/amande.jpg');
insert into Produit values (38,1,'Anone ', '0', '/resources/produits/images/anone.jpg');
insert into Produit values (39,4,'Asperge ', '0', '/resources/produits/images/asperges.jpg');
insert into Produit values (40,4,'Aubergine ', '0', '/resources/produits/images/aubergine.jpg');
insert into Produit values (41,4,'Avocat ', '0', '/resources/produits/images/avocat.jpg');
insert into Produit values (42,4,'Betterave ', '0', '/resources/produits/images/betterave.jpg');
insert into Produit values (43,4,'Blette ', '0', '/resources/produits/images/blette.jpg');
insert into Produit values (44,4,'Brocoli ', '0', '/resources/produits/images/brocoli.jpg');
insert into Produit values (45,1,'Carambole ', '0', '/resources/produits/images/carambole.jpg');
insert into Produit values (46,1,'Carotte ', '0', '/resources/produits/images/carotte.jpg');
insert into Produit values (47,4,'Cassis ', '0', '/resources/produits/images/cassis.jpg');
insert into Produit values (48,1,'Celeri-branche ', '0', '/resources/produits/images/celeri-branche.jpg');
insert into Produit values (49,1,'Celeri-rave ', '0', '/resources/produits/images/celeri-rave.jpg');
insert into Produit values (50,1,'Cepe ', '0', '/resources/produits/images/cepe.jpg');
insert into Produit values (51,4,'Cerise ', '0', '/resources/produits/images/cerise.jpg');
insert into Produit values (52,1,'Champignon de Paris ', '0', '/resources/produits/images/champignon.jpg');
insert into Produit values (53,1,'Champignons cultives ', '0', '/resources/produits/images/champignons.jpg');
insert into Produit values (54,4,'Chataigne ', '0', '/resources/produits/images/chataigne.jpg');
insert into Produit values (55,1,'Chicoree ', '0', '/resources/produits/images/chicoree.jpg');
insert into Produit values (56,1,'Chou kale ', '0', '/resources/produits/images/chou-kale.jpg');
insert into Produit values (57,1,'Chou pomme ', '0', '/resources/produits/images/chou-pomme.jpg');
insert into Produit values (58,1,'Chou-fleur ', '0', '/resources/produits/images/chou-fleur.jpg');
insert into Produit values (59,1,'Choux de Bruxelles ', '0', '/resources/produits/images/chou-de-bruxelles.jpg');
insert into Produit values (60,4,'Citron, Citron vert ', '0', '/resources/produits/images/citron.jpg');
insert into Produit values (61,1,'Clementine, Mandarine ', '0', '/resources/produits/images/clementine.jpg');
insert into Produit values (62,1,'Coing ', '0', '/resources/produits/images/coing.jpg');
insert into Produit values (63,4,'Concombre ', '0', '/resources/produits/images/concombre.jpg');
insert into Produit values (64,4,'Courges et potirons ', '0', '/resources/produits/images/courges.jpg');
insert into Produit values (65,4,'Courgette ', '0', '/resources/produits/images/courgette.jpg');
insert into Produit values (66,4,'Cresson ', '0', '/resources/produits/images/.jpg');
insert into Produit values (67,1,'Datte ', '0', '/resources/produits/images/datte.jpg');
insert into Produit values (68,4,'Echalote ', '0', '/resources/produits/images/echalote.jpg');
insert into Produit values (69,4,'Endive ', '0', '/resources/produits/images/endive.jpg');
insert into Produit values (70,4,'Epinard ', '0', '/resources/produits/images/epinard.jpg');
insert into Produit values (71,4,'Fenouil ', '0', '/resources/produits/images/fenouil.jpg');
insert into Produit values (72,4,'Feve ', '0', '/resources/produits/images/feve.jpg');
insert into Produit values (73,1,'Figue ', '0', '/resources/produits/images/figue.jpg');
insert into Produit values (74,1,'Figue de Barbarie ', '0', '/resources/produits/images/figue-barbarie.jpg');
insert into Produit values (75,4,'Fleurs comestibles ', '0', '/resources/produits/images/fleur-comestible.jpg');
insert into Produit values (76,1,'Fraise ', '0', '/resources/produits/images/fraise.jpg');
insert into Produit values (77,1,'Framboise ', '0', '/resources/produits/images/framboise.jpg');
insert into Produit values (78,1,'Fruit de la passion ', '0', '/resources/produits/images/fruit-de-la-passion.jpg');
insert into Produit values (79,1,'Fruits exotiques ', '0', '/resources/produits/images/fruits-exotiques.jpg');
insert into Produit values (80,4,'Germe de haricot ou Soja ', '0', '/resources/produits/images/haricot-mungo.jpg');
insert into Produit values (81,1,'Goyave ', '0', '/resources/produits/images/goyave.jpg');
insert into Produit values (82,1,'Grenade ', '0', '/resources/produits/images/grenade.jpg');
insert into Produit values (83,1,'Groseille ', '0', '/resources/produits/images/groseille.jpg');
insert into Produit values (84,4,'Haricot vert ', '0', '/resources/produits/images/haricot-vert.jpg');
insert into Produit values (85,4,'Herbes aromatiques fraîches ', '0', '/resources/produits/images/herbes_fraiches.jpg');
insert into Produit values (86,1,'Kaki ', '0', '/resources/produits/images/kaki.jpg');
insert into Produit values (87,1,'Kiwi ', '0', '/resources/produits/images/kiwi.jpg');
insert into Produit values (88,4,'Laitue ', '0', '/resources/produits/images/laitue.jpg');
insert into Produit values (89,4,'Lentille ', '0', '/resources/produits/images/lentille.jpg');
insert into Produit values (90,1,'Litchi ', '0', '/resources/produits/images/litchi.jpg');
insert into Produit values (91,4,'Mache ', '0', '/resources/produits/images/mache.jpg');
insert into Produit values (92,1,'Mangoustan ', '0', '/resources/produits/images/mangoustan.jpg');
insert into Produit values (93,1,'Mangue ', '0', '/resources/produits/images/mangue.jpg');
insert into Produit values (94,1,'Melon ', '0', '/resources/produits/images/melon.jpg');
insert into Produit values (95,1,'Mirabelle ', '0', '/resources/produits/images/mirabelle.jpg');
insert into Produit values (96,4,'Morille ', '0', '/resources/produits/images/morille.jpg');
insert into Produit values (97,1,'Mure ', '0', '/resources/produits/images/mure.jpg');
insert into Produit values (98,1,'Myrtille ', '0', '/resources/produits/images/myrtille.jpg');
insert into Produit values (99,4,'Navet ', '0', '/resources/produits/images/navet.jpg');
insert into Produit values (100,2,'Noisette ', '0', '/resources/produits/images/noisette.jpg');
insert into Produit values (101,2,'Noix ', '0', '/resources/produits/images/noix.jpg');
insert into Produit values (102,1,'Noix de coco ', '0', '/resources/produits/images/noix-de-coco.jpg');
insert into Produit values (103,4,'Oignon ', '0', '/resources/produits/images/oignon.jpg');
insert into Produit values (104,1,'Orange ', '0', '/resources/produits/images/orange.jpg');
insert into Produit values (105,4,'Oseille ', '0', '/resources/produits/images/oseille.jpg');
insert into Produit values (106,4,'Panais ', '0', '/resources/produits/images/panais.jpg');
insert into Produit values (107,1,'Papaye ', '0', '/resources/produits/images/papaye.jpg');
insert into Produit values (108,1,'Pasteque ', '0', '/resources/produits/images/pasteque.jpg');
insert into Produit values (109,4,'Patate douce ', '0', '/resources/produits/images/patate-douce.jpg');
insert into Produit values (110,1,'Peche, Nectarine ', '0', '/resources/produits/images/peche.jpg');
insert into Produit values (111,4,'Persil ', '0', '/resources/produits/images/persil.jpg');
insert into Produit values (112,4,'Petit pois ', '0', '/resources/produits/images/petit-pois.jpg');
insert into Produit values (113,1,'Physalis ', '0', '/resources/produits/images/physalis.jpg');
insert into Produit values (114,2,'Pignon de pin ', '0', '/resources/produits/images/pignon-de-pin.jpg');
insert into Produit values (115,4,'Pitaya ', '0', '/resources/produits/images/pitaya.jpg');
insert into Produit values (116,1,'Poire ', '0', '/resources/produits/images/poire.jpg');
insert into Produit values (117,4,'Poireau ', '0', '/resources/produits/images/poireau.jpg');
insert into Produit values (118,4,'Pois gourmand ', '0', '/resources/produits/images/pois-gourmand.jpg');
insert into Produit values (119,4,'Poivron ', '0', '/resources/produits/images/poivron.jpg');
insert into Produit values (120,1,'Pomelo ', '0', '/resources/produits/images/pomelo.jpg');
insert into Produit values (121,1,'Pomme ', '0', '/resources/produits/images/pomme.jpg');
insert into Produit values (122,4,'Pomme de terre ', '0', '/resources/produits/images/pomme-de-terre.jpg');
insert into Produit values (123,4,'Potiron ', '0', '/resources/produits/images/potiron.jpg');
insert into Produit values (124,4,'Pourpier ', '0', '/resources/produits/images/pourpier.jpg');
insert into Produit values (125,1,'Prune ', '0', '/resources/produits/images/prune.jpg');
insert into Produit values (126,4,'Radis ', '0', '/resources/produits/images/radis.jpg');
insert into Produit values (127,1,'Raisin ', '0', '/resources/produits/images/raison_chasselas.jpg');
insert into Produit values (128,1,'Rhubarbe ', '0', '/resources/produits/images/rhubarbe.jpg');
insert into Produit values (129,4,'Rutabaga ', '0', '/resources/produits/images/rutabaga.jpg');
insert into Produit values (130,4,'Salades ', '0', '/resources/produits/images/salades.jpg');
insert into Produit values (131,4,'Sapotille ', '0', '/resources/produits/images/sapotille.jpg');
insert into Produit values (132,4,'Tomate', '0', '/resources/produits/images/tomate.jpg');
insert into Produit values (133,4,'Topinambour', '0', '/resources/produits/images/topinambour.jpg');
insert into Produit values (134,4,'Truffe', '0', '/resources/produits/images/truffe.jpg');
commit;